version: '3.7'

services:
  foss-app:
    build: .
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=foss.mec.ac.in
      - VIRTUALPORT=3000
    restart: unless-stopped
    
     
  foss-app-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
#    ports:
#      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev


networks:
   default:
     external:
        name: mec

